name: crowdin

on:
  push:
    branches: [ master ]
    paths: 
      - 'module/weboot/locales/strings/*.xml'
      - '*.md'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}

jobs:
  synchronize-md:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Crowdin Action
      uses: crowdin/github-action@v2
      with:
        upload_sources: true
        upload_translations: true
        import_eq_suggestions: true
        download_translations: true
        skip_untranslated_files: true
        skip_untranslated_strings: false

        create_pull_request: true
        localization_branch_name: crowdin_docs
        pull_request_labels: 'enhancement, documentation'
        pull_request_title: 'documentation: sync translation from Crowdin'

        config: 'crowdin_md.yml'
        crowdin_branch_name: master

  synchronize-xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Crowdin Action
      uses: crowdin/github-action@v2
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        skip_untranslated_files: false
        skip_untranslated_strings: true

        create_pull_request: true
        localization_branch_name: crowdin_xml
        pull_request_labels: 'enhancement, documentation'
        pull_request_title: 'webui/locales: sync translation from Crowdin'

        config: 'crowdin_xml.yml'
        crowdin_branch_name: master
